//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.34209
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaaSCloud.Authenticate {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AUTH_SVC_RT", Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/")]
    public enum AUTH_SVC_RT : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SUCCESS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAIL_SVC_NOTEXIST = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAIL_ORG_NOTEXIST = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAIL_TOKEN_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FAIL_OTHER = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/", ConfigurationName="Authenticate.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: 命名空間 https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/ 的元素名稱  userPrincipalName 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/IsAuthenticated", ReplyAction="*")]
        SaaSCloud.Authenticate.IsAuthenticatedResponse IsAuthenticated(SaaSCloud.Authenticate.IsAuthenticatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/IsAuthenticated", ReplyAction="*")]
        System.Threading.Tasks.Task<SaaSCloud.Authenticate.IsAuthenticatedResponse> IsAuthenticatedAsync(SaaSCloud.Authenticate.IsAuthenticatedRequest request);
        
        // CODEGEN: 命名空間 https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/ 的元素名稱  Token 未標示為 nillable，正在產生訊息合約
        [System.ServiceModel.OperationContractAttribute(Action="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/CheckAuthorizedSvc", ReplyAction="*")]
        SaaSCloud.Authenticate.CheckAuthorizedSvcResponse CheckAuthorizedSvc(SaaSCloud.Authenticate.CheckAuthorizedSvcRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/CheckAuthorizedSvc", ReplyAction="*")]
        System.Threading.Tasks.Task<SaaSCloud.Authenticate.CheckAuthorizedSvcResponse> CheckAuthorizedSvcAsync(SaaSCloud.Authenticate.CheckAuthorizedSvcRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticated", Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/", Order=0)]
        public SaaSCloud.Authenticate.IsAuthenticatedRequestBody Body;
        
        public IsAuthenticatedRequest() {
        }
        
        public IsAuthenticatedRequest(SaaSCloud.Authenticate.IsAuthenticatedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/")]
    public partial class IsAuthenticatedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userPrincipalName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public IsAuthenticatedRequestBody() {
        }
        
        public IsAuthenticatedRequestBody(string userPrincipalName, string password) {
            this.userPrincipalName = userPrincipalName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticatedResponse", Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/", Order=0)]
        public SaaSCloud.Authenticate.IsAuthenticatedResponseBody Body;
        
        public IsAuthenticatedResponse() {
        }
        
        public IsAuthenticatedResponse(SaaSCloud.Authenticate.IsAuthenticatedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/")]
    public partial class IsAuthenticatedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool IsAuthenticatedResult;
        
        public IsAuthenticatedResponseBody() {
        }
        
        public IsAuthenticatedResponseBody(bool IsAuthenticatedResult) {
            this.IsAuthenticatedResult = IsAuthenticatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAuthorizedSvcRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAuthorizedSvc", Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/", Order=0)]
        public SaaSCloud.Authenticate.CheckAuthorizedSvcRequestBody Body;
        
        public CheckAuthorizedSvcRequest() {
        }
        
        public CheckAuthorizedSvcRequest(SaaSCloud.Authenticate.CheckAuthorizedSvcRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/")]
    public partial class CheckAuthorizedSvcRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Token;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OrgDomain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ServiceId;
        
        public CheckAuthorizedSvcRequestBody() {
        }
        
        public CheckAuthorizedSvcRequestBody(string Token, string OrgDomain, string ServiceId) {
            this.Token = Token;
            this.OrgDomain = OrgDomain;
            this.ServiceId = ServiceId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckAuthorizedSvcResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckAuthorizedSvcResponse", Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/", Order=0)]
        public SaaSCloud.Authenticate.CheckAuthorizedSvcResponseBody Body;
        
        public CheckAuthorizedSvcResponse() {
        }
        
        public CheckAuthorizedSvcResponse(SaaSCloud.Authenticate.CheckAuthorizedSvcResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://cmw.hisales.hinet.net/ISVAccountAuthenticationService/")]
    public partial class CheckAuthorizedSvcResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public SaaSCloud.Authenticate.AUTH_SVC_RT CheckAuthorizedSvcResult;
        
        public CheckAuthorizedSvcResponseBody() {
        }
        
        public CheckAuthorizedSvcResponseBody(SaaSCloud.Authenticate.AUTH_SVC_RT CheckAuthorizedSvcResult) {
            this.CheckAuthorizedSvcResult = CheckAuthorizedSvcResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SaaSCloud.Authenticate.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SaaSCloud.Authenticate.ServiceSoap>, SaaSCloud.Authenticate.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaaSCloud.Authenticate.IsAuthenticatedResponse SaaSCloud.Authenticate.ServiceSoap.IsAuthenticated(SaaSCloud.Authenticate.IsAuthenticatedRequest request) {
            return base.Channel.IsAuthenticated(request);
        }
        
        public bool IsAuthenticated(string userPrincipalName, string password) {
            SaaSCloud.Authenticate.IsAuthenticatedRequest inValue = new SaaSCloud.Authenticate.IsAuthenticatedRequest();
            inValue.Body = new SaaSCloud.Authenticate.IsAuthenticatedRequestBody();
            inValue.Body.userPrincipalName = userPrincipalName;
            inValue.Body.password = password;
            SaaSCloud.Authenticate.IsAuthenticatedResponse retVal = ((SaaSCloud.Authenticate.ServiceSoap)(this)).IsAuthenticated(inValue);
            return retVal.Body.IsAuthenticatedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaaSCloud.Authenticate.IsAuthenticatedResponse> SaaSCloud.Authenticate.ServiceSoap.IsAuthenticatedAsync(SaaSCloud.Authenticate.IsAuthenticatedRequest request) {
            return base.Channel.IsAuthenticatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaaSCloud.Authenticate.IsAuthenticatedResponse> IsAuthenticatedAsync(string userPrincipalName, string password) {
            SaaSCloud.Authenticate.IsAuthenticatedRequest inValue = new SaaSCloud.Authenticate.IsAuthenticatedRequest();
            inValue.Body = new SaaSCloud.Authenticate.IsAuthenticatedRequestBody();
            inValue.Body.userPrincipalName = userPrincipalName;
            inValue.Body.password = password;
            return ((SaaSCloud.Authenticate.ServiceSoap)(this)).IsAuthenticatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SaaSCloud.Authenticate.CheckAuthorizedSvcResponse SaaSCloud.Authenticate.ServiceSoap.CheckAuthorizedSvc(SaaSCloud.Authenticate.CheckAuthorizedSvcRequest request) {
            return base.Channel.CheckAuthorizedSvc(request);
        }
        
        public SaaSCloud.Authenticate.AUTH_SVC_RT CheckAuthorizedSvc(string Token, string OrgDomain, string ServiceId) {
            SaaSCloud.Authenticate.CheckAuthorizedSvcRequest inValue = new SaaSCloud.Authenticate.CheckAuthorizedSvcRequest();
            inValue.Body = new SaaSCloud.Authenticate.CheckAuthorizedSvcRequestBody();
            inValue.Body.Token = Token;
            inValue.Body.OrgDomain = OrgDomain;
            inValue.Body.ServiceId = ServiceId;
            SaaSCloud.Authenticate.CheckAuthorizedSvcResponse retVal = ((SaaSCloud.Authenticate.ServiceSoap)(this)).CheckAuthorizedSvc(inValue);
            return retVal.Body.CheckAuthorizedSvcResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SaaSCloud.Authenticate.CheckAuthorizedSvcResponse> SaaSCloud.Authenticate.ServiceSoap.CheckAuthorizedSvcAsync(SaaSCloud.Authenticate.CheckAuthorizedSvcRequest request) {
            return base.Channel.CheckAuthorizedSvcAsync(request);
        }
        
        public System.Threading.Tasks.Task<SaaSCloud.Authenticate.CheckAuthorizedSvcResponse> CheckAuthorizedSvcAsync(string Token, string OrgDomain, string ServiceId) {
            SaaSCloud.Authenticate.CheckAuthorizedSvcRequest inValue = new SaaSCloud.Authenticate.CheckAuthorizedSvcRequest();
            inValue.Body = new SaaSCloud.Authenticate.CheckAuthorizedSvcRequestBody();
            inValue.Body.Token = Token;
            inValue.Body.OrgDomain = OrgDomain;
            inValue.Body.ServiceId = ServiceId;
            return ((SaaSCloud.Authenticate.ServiceSoap)(this)).CheckAuthorizedSvcAsync(inValue);
        }
    }
}
